# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='filr_type',
            new_name='file_type',
        ),
    ]
